Bump version for lix sample
dart-lang/samples pull request #75
Opened 2020-10-10 17:34 UTC by timsneath

Current version is incompatible with what's on the Flutter `master` channel.

2020-10-10 20:20 UTC, domesticmouse approved these changes

2020-10-10 22:38 UTC, timsneath commented
Holding back a moment, since @aam commented on another issue that suggested this SDK constraint might be too broad. Waiting for a consistent verdict here that we can then make sure we apply across the board.

2020-10-19 14:47 UTC, mit-mit commented
@timsneath thanks for updating this! I believe the correct upper constraint (as discussed e.g. in https://github.com/dart-lang/sdk/issues/43757#issuecomment-707371249) is to use an upper constraint of `<2.12.0` to express that until the feature is stable we should not make claims about forward compatibility.

2020-10-19 14:47 UTC, mit-mit requested changes

2020-10-19 14:47 UTC, mit-mit commented on null_safety/calculate_lix/pubspec.yaml
> +  sdk: '>=2.10.0-56.0.dev <3.0.0'
Should use `<2.12.0`

2020-10-20 15:24 UTC, mit-mit commented
It would also be great to add something like this to `/calculate_lix/README.md`:

```
--- a/null_safety/calculate_lix/README.md
+++ b/null_safety/calculate_lix/README.md
@@ -41,6 +41,10 @@ To run the main app, type these commands in the terminal/command-prompt:
     - `/Users/michael/dev/preview/dart-sdk/bin/dart pub get`
     - `/Users/michael/dev/preview/dart-sdk/bin/dart --enable-experiment=non-nullable run bin/main.dart text/lorem-ipsum.txt`

+*Note*: You may see a warning "Overriding the upper bound Dart SDK constraint"
+when running pub get. You can ignore this, which is a temporary issue only
+expected during preview.
+
 ### Running from VSCode
```

2020-10-21 21:29 UTC, mit-mit approved these changes

2020-10-21 21:30 UTC, merged